 steps:
  - name: "gcr.io/portablefridge-311105/firebase"
    args: ['deploy', '--project=portablefridge-311105', '--only=hosting']
 #cloudbuild.yaml
#steps:
   #build & push the container image

#- name: "gcr.io/kaniko-project/executor:v0.12.0"
  #args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/portable-fridge-c194f/user:latest"]
   #Deploy container image to Cloud Run
#- name: "gcr.io/cloud-builders/gcloud"
  #args: ['beta', 'run', 'deploy', 'fridge', '--image', 'gcr.io/portable-fridge-c194f/user:latest', '--region', 'us-west3', '--allow-unauthenticated', '--platform', 'managed']
